import { RegiaoAnatomica } from "../interfaces/regioes.interface";

export const REGIOES_ANTERIORES: RegiaoAnatomica[] = [
  { codigo: 1, nome: "Frontal", lateralidades: ["MEDIANA"] },
  { codigo: 2, nome: "Orbitárias", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 3, nome: "Malares", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 4, nome: "Mandibular", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 5, nome: "Mentoniana", lateralidades: ["MEDIANA"] },
  { codigo: 6, nome: "Cervical anterior", lateralidades: ["MEDIANA"] },
  { codigo: 7, nome: "Carotidianas", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 8, nome: "Supraclaviculares", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 9, nome: "Infraclaviculares", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 10, nome: "Esternal", lateralidades: ["MEDIANA"] },
  { codigo: 11, nome: "Torácicas", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 12, nome: "Epigástricas", lateralidades: ["MEDIANA"] },
  { codigo: 13, nome: "Hipocôndrios", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 14, nome: "Mesogástrica", lateralidades: ["MEDIANA"] },
  { codigo: 15, nome: "Flancos", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 16, nome: "Hipogástrica", lateralidades: ["MEDIANA"] },
  { codigo: 17, nome: "Fossas ilíacas", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 18, nome: "Pubiana", lateralidades: ["MEDIANA"] },
  { codigo: 19, nome: "Inguinal", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 20, nome: "Escrotal", lateralidades: ["NAO_APLICAVEL"] },
  { codigo: 21, nome: "Braço", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 22, nome: "Cubital", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 23, nome: "Antebraço", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 24, nome: "Palmar", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 25, nome: "Coxa", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 26, nome: "Joelho", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 27, nome: "Perna", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 28, nome: "Dorso do pé", lateralidades: ["DIREITA","ESQUERDA"] }
];

export const REGIOES_POSTERIORES: RegiaoAnatomica[] = [
  { codigo: 1, nome: "Parietal", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 2, nome: "Occipital", lateralidades: ["MEDIANA"] },
  { codigo: 3, nome: "Temporal", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 4, nome: "Cervical", lateralidades: ["MEDIANA"] },
  { codigo: 5, nome: "Supra-escapular", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 6, nome: "Escapular", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 7, nome: "Dorsal", lateralidades: ["MEDIANA"] },
  { codigo: 8, nome: "Lombar", lateralidades: ["MEDIANA"] },
  { codigo: 9, nome: "Ilíaca", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 10, nome: "Espondiléia", lateralidades: ["MEDIANA"] },
  { codigo: 11, nome: "Sacro-coccígea", lateralidades: ["MEDIANA"] },
  { codigo: 12, nome: "Glútea", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 13, nome: "Coxa", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 14, nome: "Poplítea", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 15, nome: "Perna", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 16, nome: "Pé", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 17, nome: "Deltoidiana", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 18, nome: "Braço", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 19, nome: "Cotovelo", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 20, nome: "Antebraço", lateralidades: ["DIREITA","ESQUERDA"] },
  { codigo: 21, nome: "Face dorsal mão", lateralidades: ["DIREITA","ESQUERDA"] }
];