export var Bairros = Array(
        'Adrianópolis',
        'Ajuricaba',
        'Aleixo',
        'Alvorada',
        'Aparecida',
        'Armando Mendes',
        'Betânia',
        'Cachoeirinha',
        'Centro',
        'Compensa',
        'Cidade de Deus',
        'Cidade Nova',
        'Coroado',
        'Crespo',
        'da Paz',
        'Distrito Industrial',
        'Distrito Industrial I',
        'Distrito Industrial II',
        'Educandos',
        'Flores',
        'Glória',
        'Japiim',
        'Jorge Teixeira',
        'Lago Azul',
        'Lírio do Vale',
        'Nossa Senhora das Graças',
        'Novo Aleixo',
        'Nova Cidade',
        'Nova Esperança',
        'Paz',
        'Petrópolis',
        'Planalto',
        'Ponta Negra',
        'Praça 14',
        'Presidente Vargas',
        'Raiz',
        'Redenção',
        'Santo Antônio',
        'Santo Agostinho',
        'São Francisco',
        'São Jorge',
        'São José',
        'São Raimundo',
        'Tancredo Neves',
        'Tarumã',
        'Terra Nova',
        'Vila da Prata',
        'Zumbi'
    );